// +build ignore

package main

import (
	"io/ioutil"
	"os"
	"text/template"
)

var packageTemplate = template.Must(template.New("").Parse("// Code generated by go generate; DO NOT EDIT.\npackage main\n\nvar pieTemplate = `{{ . }}`\n"))

func main() {
	tmpl, err := ioutil.ReadFile("pie.go")
	if err != nil {
		panic(err)
	}

	f, err := os.Create("template.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	packageTemplate.Execute(f, string(tmpl))
}
