// +build ignore

package main

import (
	"io/ioutil"
	"os"
	"text/template"
)

var packageTemplate = template.Must(template.New("").
	Parse("// Code generated by go generate; DO NOT EDIT.\npackage main\n\nvar pieAllTemplate = `{{ .All }}`\n\nvar pieStringsNumbersTemplate = `{{ .StringsNumbers }}`\n\nvar pieNumbersTemplate = `{{ .Numbers }}`\n"))

func main() {
	files := map[string]string{
		"All":            "pie_all.go",
		"StringsNumbers": "pie_strings_numbers.go",
		"Numbers":        "pie_numbers.go",
	}
	data := map[string]string{}

	for key, file := range files {
		tmpl, err := ioutil.ReadFile(file)
		if err != nil {
			panic(err)
		}

		data[key] = string(tmpl)
	}

	f, err := os.Create("template.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	packageTemplate.Execute(f, data)
}
